# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'init.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1110, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1110, 700))
        Form.setMaximumSize(QtCore.QSize(1110, 700))
        self.test_name = QtWidgets.QLabel(Form)
        self.test_name.setGeometry(QtCore.QRect(110, 90, 921, 55))
        font = QtGui.QFont()
        font.setFamily("Lohit Tamil")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.test_name.setFont(font)
        self.test_name.setTextFormat(QtCore.Qt.AutoText)
        self.test_name.setAlignment(QtCore.Qt.AlignCenter)
        self.test_name.setObjectName("test_name")
        self.q_numb = QtWidgets.QLabel(Form)
        self.q_numb.setGeometry(QtCore.QRect(470, 230, 156, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans Extrabold")
        font.setBold(True)
        font.setWeight(75)
        self.q_numb.setFont(font)
        self.q_numb.setAlignment(QtCore.Qt.AlignCenter)
        self.q_numb.setObjectName("q_numb")
        self.VAS = QtWidgets.QLabel(Form)
        self.VAS.setGeometry(QtCore.QRect(10, 60, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VAS.sizePolicy().hasHeightForWidth())
        self.VAS.setSizePolicy(sizePolicy)
        self.VAS.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.VAS.setFont(font)
        self.VAS.setMouseTracking(False)
        self.VAS.setAlignment(QtCore.Qt.AlignCenter)
        self.VAS.setObjectName("VAS")
        self.start_but = QtWidgets.QPushButton(Form)
        self.start_but.setGeometry(QtCore.QRect(400, 550, 291, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_but.sizePolicy().hasHeightForWidth())
        self.start_but.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("DejaVu Sans")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.start_but.setFont(font)
        self.start_but.setObjectName("start_but")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(330, 420, 51, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(51, 25))
        self.label_3.setMaximumSize(QtCore.QSize(51, 25))
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(260, 470, 117, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(117, 25))
        self.label_5.setMaximumSize(QtCore.QSize(117, 25))
        self.label_5.setObjectName("label_5")
        self.fio_edit = QtWidgets.QLineEdit(Form)
        self.fio_edit.setGeometry(QtCore.QRect(390, 420, 301, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fio_edit.sizePolicy().hasHeightForWidth())
        self.fio_edit.setSizePolicy(sizePolicy)
        self.fio_edit.setMinimumSize(QtCore.QSize(301, 25))
        self.fio_edit.setMaximumSize(QtCore.QSize(301, 25))
        self.fio_edit.setObjectName("fio_edit")
        self.per_numb = QtWidgets.QLineEdit(Form)
        self.per_numb.setGeometry(QtCore.QRect(390, 470, 301, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.per_numb.sizePolicy().hasHeightForWidth())
        self.per_numb.setSizePolicy(sizePolicy)
        self.per_numb.setMinimumSize(QtCore.QSize(301, 25))
        self.per_numb.setMaximumSize(QtCore.QSize(301, 25))
        self.per_numb.setObjectName("per_numb")
        self.time_limit = QtWidgets.QLabel(Form)
        self.time_limit.setGeometry(QtCore.QRect(400, 280, 290, 22))
        font = QtGui.QFont()
        font.setFamily("Open Sans Extrabold")
        self.time_limit.setFont(font)
        self.time_limit.setAlignment(QtCore.Qt.AlignCenter)
        self.time_limit.setObjectName("time_limit")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(420, 360, 231, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Open Sans Condensed")
        font.setPointSize(15)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(230, 330, 651, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.test_name.setText(_translate("Form", "Тестирование  по Истории войск связи"))
        self.q_numb.setText(_translate("Form", "Кол-во вопросов: N"))
        self.VAS.setText(_translate("Form", "TextLabel"))
        self.start_but.setText(_translate("Form", "Начать"))
        self.label_3.setText(_translate("Form", "ФИО:"))
        self.label_5.setText(_translate("Form", "Личный номер:"))
        self.fio_edit.setPlaceholderText(_translate("Form", "                   Фамилия Имя Отчество"))
        self.per_numb.setPlaceholderText(_translate("Form", "                                    56789"))
        self.time_limit.setText(_translate("Form", "Время выполнения: неограниченно"))
        self.label_7.setText(_translate("Form", " Персональные данные"))

