# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'quest.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1110, 700)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setMinimumSize(QtCore.QSize(1110, 700))
        Form.setMaximumSize(QtCore.QSize(1110, 700))
        self.test_name = QtWidgets.QLabel(Form)
        self.test_name.setGeometry(QtCore.QRect(110, 90, 921, 55))
        font = QtGui.QFont()
        font.setFamily("Lohit Tamil")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.test_name.setFont(font)
        self.test_name.setTextFormat(QtCore.Qt.AutoText)
        self.test_name.setAlignment(QtCore.Qt.AlignCenter)
        self.test_name.setObjectName("test_name")
        self.VAS = QtWidgets.QLabel(Form)
        self.VAS.setGeometry(QtCore.QRect(10, 60, 100, 100))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.VAS.sizePolicy().hasHeightForWidth())
        self.VAS.setSizePolicy(sizePolicy)
        self.VAS.setMinimumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        self.VAS.setFont(font)
        self.VAS.setMouseTracking(False)
        self.VAS.setAlignment(QtCore.Qt.AlignCenter)
        self.VAS.setObjectName("VAS")
        self.first_ans = QtWidgets.QRadioButton(Form)
        self.first_ans.setGeometry(QtCore.QRect(360, 450, 371, 23))
        self.first_ans.setObjectName("first_ans")
        self.second_ans = QtWidgets.QRadioButton(Form)
        self.second_ans.setGeometry(QtCore.QRect(360, 480, 371, 23))
        self.second_ans.setObjectName("second_ans")
        self.third_ans = QtWidgets.QRadioButton(Form)
        self.third_ans.setGeometry(QtCore.QRect(360, 510, 371, 23))
        self.third_ans.setMinimumSize(QtCore.QSize(371, 0))
        self.third_ans.setObjectName("third_ans")
        self.fourth_ans = QtWidgets.QRadioButton(Form)
        self.fourth_ans.setGeometry(QtCore.QRect(360, 540, 371, 23))
        self.fourth_ans.setMinimumSize(QtCore.QSize(371, 0))
        self.fourth_ans.setObjectName("fourth_ans")
        self.phrase = QtWidgets.QLabel(Form)
        self.phrase.setGeometry(QtCore.QRect(70, 190, 971, 81))
        self.phrase.setAlignment(QtCore.Qt.AlignCenter)
        self.phrase.setObjectName("phrase")
        self.quest_numb = QtWidgets.QLabel(Form)
        self.quest_numb.setGeometry(QtCore.QRect(500, 320, 121, 21))
        self.quest_numb.setObjectName("quest_numb")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(380, 250, 341, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.quest = QtWidgets.QLabel(Form)
        self.quest.setGeometry(QtCore.QRect(160, 360, 751, 51))
        self.quest.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.quest.setObjectName("quest")
        self.line_3 = QtWidgets.QFrame(Form)
        self.line_3.setGeometry(QtCore.QRect(380, 200, 341, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(890, 620, 170, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(170, 0))
        self.pushButton.setMaximumSize(QtCore.QSize(170, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setGeometry(QtCore.QRect(700, 620, 170, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(170, 0))
        self.pushButton_2.setMaximumSize(QtCore.QSize(170, 16777215))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.test_name.setText(_translate("Form", "Тестирование  по Истории войск связи"))
        self.VAS.setText(_translate("Form", "TextLabel"))
        self.first_ans.setText(_translate("Form", " i don\'t now nothing"))
        self.second_ans.setText(_translate("Form", "my wife is better"))
        self.third_ans.setText(_translate("Form", "(just a smile) :)"))
        self.fourth_ans.setText(_translate("Form", "funny stufy bunny"))
        self.phrase.setText(_translate("Form", "Какая-то длинная и очень умная фраза из источника про что-нибудь военное и очень поучительое"))
        self.quest_numb.setText(_translate("Form", "Вопрос №"))
        self.quest.setText(_translate("Form", "Вопросительный вопрос в котором нет конкретики но конкретика содеражится в проваописании \n"
" и наречий "))
        self.pushButton.setText(_translate("Form", "следующий"))
        self.pushButton_2.setText(_translate("Form", "предыдущий"))

